### ISSUE TITLE
Wrap messages (frames/predictions) in objects

### ISSUE THREAD

**Issue by sionovd** [ItamarWilf/PipeRT#12]
We need to make sure that the data that we send to/receive from the redis server is wrapped in an object. The object would hold information such as a history of which components the message passed through, timestamps that indicate when it entered/left a component, a message id, the source stream address, and anything else that could prove useful later on when monitoring the messages. 
Additionally, the message contains a payload, which holds the actual data (frame or prediction) as well as other relevant information specific to that data (for example, the dimensions of the frame).

**Comment by ItamarWilf** [comment]
Fixed in #16 .
