### ISSUE TITLE
Decouple visualization from Detectron2

### ISSUE THREAD

**Issue by ItamarWilf** [ItamarWilf/PipeRT#13]
Facebook's Detectron2 have a great visualizer, but we want to use the same functionality without installing and importing the entire Detectron2 lib. We need to copy/decouple the MetadataCatalog from the visualizer and find another way to pass the visualization params.

**Comment by OmriKaduri** [comment]
@ItamarWilf @sionovd I think you guys already did it. If so, close the issue

**Comment by sionovd** [comment]
@ItamarWilf @MayoG @ItayHoresh it looks like there is a [pre-built version of detectron2](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#install-pre-built-detectron2). Should we still bother with this issue if the pre-built version works well? 

I personally tried it and it works for the display. But I noticed that the pose-estimation component uses detectron2 as well, so maybe one of you guys can check to see if there are no problems there.

**Comment by ItayHoresh** [comment]
@sionovd it sounds nice, but I saw that it requires extra installations.
 We need to get into it.
