### ISSUE TITLE
Fix RedisHandler to not read the same messages

### ISSUE THREAD

**Issue by MayoG** [ItamarWilf/PipeRT#21]
In order to do that, we need to save the id of the last message that we read and use the functionality of xrevrange to read the last message of the stream from the last id.

xrevrange documentation: https://redis-py.readthedocs.io/en/latest/index.html#redis.Redis.xrevrange

**Comment by ItamarWilf** [comment]
Thank you @MayoG, now that #16 is merged into the master branch you can go ahead and implement it. You can ask @sionovd for help with #16.
While at it, can you implement it for both a `read_next_msg` and `read_most_recent_msg` methods?
