### ISSUE TITLE
Add monitoring dashboard

### ISSUE THREAD

**Issue by ItamarWilf** [ItamarWilf/PipeRT#24]
Depends on #22 

Use `Prometheus` and `Grafana` to build a dashboard displaying data about the throughput and latency of each component in the pipeline, and the pipeline as a whole. This can be done using the metadata recorded with each message and the prometheus-python client.
Also, the prometheus and grafana dockers should be added to the pipeline's docker-compose.

**Comment by OmriKaduri** [comment]
Why does the prometheus and grafana dockers should be added to the compose file? Seems like their addresses should be configurable, in cases we'll want to deploy the pipeline at environments with managed services.
