### ISSUE TITLE
Add pacer to routine

### ISSUE THREAD

**Issue by ItamarWilf** [ItamarWilf/PipeRT#4]
Used for keeping the pace of a certain routine at a certain FPS even if the routine could run faster, so to not put too much on other parts of the pipeline. For example, if the routine is reading frames from a video file, we want  to set its pacer at 30 frames per second to slow down the stream of frames so it won't cause the rest of the pipeline to crash.

The pacer should be optional, and take into account the mean latency of the routine as well as the possible fluctuations. It could be added to a routine by using the `add event handler`.

The pacer is not responsible for dropping frames in case of growing latency, that should be another feature.

**Comment by Elon-Abulafia** [comment]
comment

**Comment by ItamarWilf** [comment]
Your'e welcome :)
