### ISSUE TITLE
Tech Review - python multiprocessing shared memory VS posix_ipc

### ISSUE THREAD

**Issue by ItamarWilf** [ItamarWilf/PipeRT#47]

**Comment by Elon-Abulafia** [comment]
From some research i performed the conclusions I got are as follows:
Multiprocessing shared memory is based on "System V style" which is the older format of using shared memory while posix_ipc uses the posix approach. The main difference is that posix is based on sys v and as such was developed with the strengths and weaknesses of sys v in mind.
As a result the posix api is a lot simpler and easier to use.
**But** the multiprocessing package was developed very recently with (as I said before) "Sys V **Style**" and as such was tuned to work with theoretically even better performance than posix.
Also the api used in multiprocessing shared memory is very very simple and easy to use, even more so than posix.
In terms of performance I couldnt find a concrete answer but from tests ran on my computer it seems that the multiprocessing shared memory is faster but less reliable (although that might be just from issues in my computer), and posix_ipc spikes in performance a lot of the time which is also very very bad when compared to using redis.
