### ISSUE TITLE
[Discussion] Config file clarification

### ISSUE THREAD

**Issue by MayoG** [ItamarWilf/PipeRT#52]
I want to make sure that i understand the purpose of the config file.
The config file is how we will set the pipeline with initial components and routines and you want me to make an explanation on how to make it ? or i didn't get this right.

@ItamarWilf @ItayHoresh @OmriKaduri

**Comment by OmriKaduri** [comment]
Hi @MayoG ,

It would be nice to see a documentation page (prefereably under [the docs](https://pipert.readthedocs.io/en/latest/?badge=latest)) which specifies what fields can be configured using the configuration file, along with an example configuration file.

**Comment by ItayHoresh** [comment]
Hi,
We need to add 3 things to the docs:
1. How to work with the cli
2. How to work with the PipeRt UI
3. The formation of the config file for running the pipe

@MayoG you need to set the formation of the valid config files.

**Comment by MayoG** [comment]
Hey, I will do everything you asked me to do but you didn't answer my question, is that a good format of conf file, it seems pretty good and easy for outsiders to make one for themselves, and of course i will make a documentation file to make it more clear.

```
[
    {
        "name": "Stream",
        "queues": ["video"],
        "routines":
        [
            {
                "routine_type_name": "ListenToStream",
                "stream_address": "0",
                "out_queue": "video",
                "fps": 30,
                "name": "capture_frame"
            },
            {
                "routine_type_name": "MessageToRedis",
                "redis_send_key": "cam",
                "message_queue": "video",
                "max_stream_length": 10,
                "name": "upload_redis"
            }
        ]
    },
    {
        "name": "Display",
        "queues": ["messages"],
        "routines":
        [
            {
                "routine_type_name": "MessageFromRedis",
                "redis_read_key": "cam",
                "message_queue": "messages",
                "name": "get_frames"
            },
            {
                "routine_type_name": "DisplayCv2",
                "frame_queue": "messages",
                "name": "draw_frames"
            }
        ]
    },
]
```

**Comment by OmriKaduri** [comment]
1. Maybe it would be nice to have an ID for a component? Then, when you'll want to look for a component (by id) it would be easier. The ID can be a string, in order to be readable.
2. Generally, my preference for configuration files is using `yaml`, because it's much more readable. What do you think?

**Comment by ItayHoresh** [comment]
1. ID is a good idea.
2. The reason @MayoG  choose json format is because of the UI. The json format will work for both cli and UI.

**Comment by OmriKaduri** [comment]
And for what reason the yaml format won't work for both cli and UI?

**Comment by MayoG** [comment]
The name is an id, all names must be unique, so its what you suggested.

**Comment by MayoG** [comment]
I think I can work with yaml, all i need to do is to parse it to a dictionary and its fine.
The example that i wrote is in python dictionary and it is similar to json. I just wanted to check if the component object is good and easy to understand.
