### ISSUE TITLE
Add option to run component as a thread or as a process

### ISSUE THREAD

**Issue by MayoG** [ItamarWilf/PipeRT#67]
Add option to run component as a thread or as a process that will be available for the configuration file and the cli.

**Comment by ItayHoresh** [comment]
@MayoG Is it another parameter that the UI must implement or we need to ask Dor to make some changes?

**Comment by MayoG** [comment]
@ItayHoresh I made it that dor's code will not get hurt and still work.
But if he want to use this option he will need to add or make some changes when creating a component and choosing the way he want it to run.
