### ISSUE TITLE
The routine DisplayCv2 not working

### ISSUE THREAD

**Issue by MayoG** [ItamarWilf/PipeRT#68]
[DisplayCv2 Routine](https://github.com/ItamarWilf/PipeRT/blob/master/pipert/contrib/routines/display_cv2.py)

We have 2 bugs with this routine:

1. When trying to activate it we get an error from the container logs that says : cannot connect to X server.

2. When we solve the first bug, we can't run this routine for the second time.
it causes an infinite loop at line 21 : `cv2.imshow(self.name, frame)`

**Comment by AmitKarin** [comment]
Is this issue is something we need to research about and handle? 
Is this routine is being used?

**Comment by ItayHoresh** [comment]
@AmitKarin  good question. I guess not because nobody mentioned it.
The reason that we should handle this routine is for stop using the flask display that must have detectron installed.

**Comment by AmitKarin** [comment]
@ItayHoresh if we fix the problem with installing detectron (which I'm trying to fix these days) we won't need this routine, right?

**Comment by ItayHoresh** [comment]
If you mean that we will not need detectron for display, the answer is yes and I don't think we need this routine.

**Comment by AmitKarin** [comment]
@ItayHoresh I think we fixed the problem with detectron . So can we delete this issue?

**Comment by ItayHoresh** [comment]
Hi @AmitKarin,
If there is no use of this routine we can delete it and then close the issue.
Create a new PR with this changes.
